/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { PerspectiveCamera, useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import gsap from "gsap";
import { Vector3 } from "three";

export function Model(props) {
    const { nodes, materials } = useGLTF("/models/hero_3d_model_baked_floor.glb");
    const rotation = {
        x: -0.04758625159436784,
        y: -0.014372534616284394,
        z: -0.0006844280910795079
    };

    useThree(({ camera }) => {
        console.log(camera.position)
        console.log(camera.fov)
        console.log(camera.rotation)
        camera.fov = 2.2
        camera.position.x = 0 // left and right x
        camera.position.z = 7.5 // forward and backward
        camera.position.y = 1.2 // mela keezha means y
        camera.zoom = 0.1
        camera.rotation.x = 0.0
        camera.updateProjectionMatrix()
        // camera.rotation.x = 10
        // gsap.from(camera.position, { x: 10, duration: 2 }) // basic gsap anim
    })

    // useFrame(() => {
    //     const eventHandler = (e) => {
    //         console.log(e.x)
    //     }
    //     window.addEventListener("mousemove", eventHandler)

    //     return () => window.removeEventListener("mousemove", eventHandler)
    // })

    return (
        <group {...props} dispose={null}>
            <PerspectiveCamera makeDefault />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={materials.wood_sticks}
                position={[-2.711, 1.287, -3.641]}
            />
            <group
                position={[-2.336, -0.003, -3.062]}
                rotation={[Math.PI, 0.693, 0]}
                scale={-0.007}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.CB2_Dauphine_Floor_Lamp_1.geometry}
                    material={materials.CB2_Dauphine_Floor_Lamp_mtl_5}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.CB2_Dauphine_Floor_Lamp_2.geometry}
                    material={nodes.CB2_Dauphine_Floor_Lamp_2.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.CB2_Dauphine_Floor_Lamp_3.geometry}
                    material={materials.wood_sticks}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.CB2_Dauphine_Floor_Lamp_4.geometry}
                    material={nodes.CB2_Dauphine_Floor_Lamp_4.material}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder.geometry}
                material={nodes.Cylinder.material}
                position={[1.463, 0.161, -2.957]}
                scale={[0.135, 0.165, 0.135]}
            />
            <group position={[0, 1.348, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube001.geometry}
                    material={materials.Wall}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube001_1.geometry}
                    material={materials["Floor.001"]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["left-shoulder"].geometry}
                material={materials.shoulder}
                position={[-3.236, 2.681, 0.374]}
                scale={[0.37, 0.638, 0.37]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["left-shoulder001"].geometry}
                material={materials.shoulder}
                position={[3.247, 2.681, 0.374]}
                scale={[0.37, 0.638, 0.37]}
            />
            <group position={[0.136, 0.277, -1.24]} scale={[1, 1.5, 1]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder011.geometry}
                    material={materials.agua}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder011_1.geometry}
                    material={materials["vidro 2"]}
                />
            </group>
            <group
                position={[-0.01, 2.482, -1.565]}
                rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                scale={0.617}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder001.geometry}
                    material={materials["metal 1"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder001_1.geometry}
                    material={materials.luz}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube059.geometry}
                material={materials["tecido 3.001"]}
                position={[-1.089, 0.55, -1.033]}
                rotation={[-0.158, 1.37, -0.042]}
            />
            <group
                position={[-1.187, 0.306, -1.164]}
                rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube071.geometry}
                    material={materials["tecido 1.001"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube071_1.geometry}
                    material={materials.madeira}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube049.geometry}
                material={materials["tecido 3"]}
                position={[-0.426, 0.562, -3.085]}
                rotation={[0, Math.PI / 2, 0]}
            />
            <group position={[0.488, 0.177, -1.518]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube019.geometry}
                    material={materials.madeira}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube019_1.geometry}
                    material={materials["pedra 1"]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube025.geometry}
                material={materials["tecido 1"]}
                position={[0.052, 0.281, -3.045]}
                rotation={[0, -Math.PI / 2, 0]}
            />
            <group
                position={[0.128, 0.575, -1.225]}
                rotation={[-1.801, 1.046, -0.952]}
                scale={[-0.01, -0.011, -0.012]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["3DGeom~42_Defintion_1"].geometry}
                    material={materials["planta 3"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["3DGeom~42_Defintion_2"].geometry}
                    material={materials["planta 3"]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube034.geometry}
                material={materials["madeira.002"]}
                position={[1.635, 0.041, -1.482]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube035.geometry}
                material={materials["tecido 1.002"]}
                position={[1.635, 0.041, -1.482]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube013.geometry}
                material={materials["madeira.002"]}
                position={[-0.291, 0.043, -2.845]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Architectu001.geometry}
                material={materials.Architectural_Ma}
                position={[0.118, 0.009, -1.507]}
                rotation={[0, 0.004, 0]}
                scale={[0.014, 0.019, 0.014]}
            />
            <group
                position={[2.055, 0.822, -3.747]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.049, 0.049, 0.063]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["3d-model_1"].geometry}
                    material={materials._0010_Snow_1}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["3d-model_2"].geometry}
                    material={materials.skp_front_default}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/hero_3d_model_baked_floor.glb");


