import Navbar from "./MenuBar/Navbar";
import HeroSection from "./HeroSection/HeroSection";
import Loader from "./Loader/Loader";
import Menu from "./Menu/Menu";
import Socials from "./Socials/Socials";
import ProjectChoice from "./ProjectChoice/ProjectChoice";
import HeroHeading from "./HeroHeading/HeroHeading";
// import Model3D from "./Model3D/Model3D";
import SwirlingSection from "./SwirlingSection/SwirlingSection";
import ScrollIndicator from "./ScrollIndicator/ScrollIndicator";
import ArchitectureGallery from "./ArchitectureGallery/ArchitectureGallery";
import InteriorGallery from "./InteriorGallery/InteriorGallery";
import HeroSlider from "./HeroSlider/HeroSlider";
import WordFromFounder from "./WordFromFounder/WordFromFounder";
import OurStory from "./OurStory/OurStory";
import GalleryBox from "./GalleryBox/GalleryBox";
import Footer from "./Footer/Footer";
import ArchitectureList from "./ArchitectureList/ArchitectureList";
import InteriorList from "./InteriorList/InteriorList";
import HomepageMobile from "./HomepageMobile/HomepageMobile";
import ScrollToTop from "./ScrollToTop/ScrollToTop";
export { Navbar, HeroSection, Menu, Loader, Socials, ProjectChoice, HeroHeading, SwirlingSection, ScrollIndicator, ArchitectureGallery, InteriorGallery, HeroSlider, WordFromFounder, OurStory, GalleryBox, Footer, ArchitectureList, InteriorList, HomepageMobile, ScrollToTop };