/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import { TextureLoader, EquirectangularReflectionMapping, ACESFilmicToneMapping } from "three"
import { RGBELoader } from "three/examples/jsm/loaders/RGBELoader"
import { useThree } from "@react-three/fiber";

export function Model(props) {
    const { nodes, materials } = useGLTF("/models/alpha_city_scene1.glb");
    // console.log(materials, cameras)

    // loading transparent texture
    const transpTexture = new TextureLoader().load('/models/cb2.png')
    materials.Material.alphaMap = transpTexture

    const { gl, scene, camera } = useThree()

    useLayoutEffect(() => {
        if (gl && scene) {
            new RGBELoader().setPath('/models/').load('/moonless_golf_1k.hdr', (texture) => {
                texture.mapping = EquirectangularReflectionMapping;
                
                texture.matrixAutoUpdate = true;
                texture.updateMatrix()
                texture.rotation = 20

                scene.background = texture;
                scene.environment = texture;
                scene.backgroundIntensity = 0.1;

                gl.toneMapping = ACESFilmicToneMapping
                gl.toneMappingExposure = 0.35
            })
            console.log(camera)
        }

    }, [gl, scene])

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Building_square_lambert1_0.geometry}
                material={materials.lambert1}
                position={[-70.24, 0, 33.772]}
                rotation={[0, -0.531, 0]}
                scale={0.007}
            />
            <group
                position={[27.152, 47.693, -65.042]}
                rotation={[0, -1.135, 0]}
                scale={0.223}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.heloPad__0.geometry}
                    material={materials.heloPad__0}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.heloPad__0_1.geometry}
                    material={materials.sails}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.heloPad__0_2.geometry}
                    material={materials.white_structure}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.heloPad__0_3.geometry}
                    material={materials.rooms}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.heloPad__0_4.geometry}
                    material={materials.heloPad}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.heloPad__0_5.geometry}
                    material={materials.base}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["12"].geometry}
                material={materials.material}
                position={[8.2, 0.303, -18.739]}
                rotation={[0, 1.102, 0]}
                scale={[30.892, 28.615, 30.892]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["10"].geometry}
                material={materials.material}
                position={[-6.947, 0.365, -9.434]}
                rotation={[0, 1.102, 0]}
                scale={34.319}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["6"].geometry}
                material={materials.material}
                position={[-5.11, 0.342, 11.803]}
                rotation={[Math.PI, -1.102, Math.PI]}
                scale={34.319}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["18"].geometry}
                material={materials.material}
                position={[-4.785, 0.362, -47.055]}
                rotation={[0, 1.102, 0]}
                scale={34.319}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["7"].geometry}
                material={materials.material}
                position={[12.438, 11.993, 25.111]}
                rotation={[0, 1.102, 0]}
                scale={51.348}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["9"].geometry}
                material={materials.material}
                position={[8.864, 0.394, -0.655]}
                rotation={[0, 1.102, 0]}
                scale={24.922}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["20"].geometry}
                material={materials.material}
                position={[-10.997, 0.201, -60.397]}
                rotation={[0, 1.102, 0]}
                scale={80.508}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["4"].geometry}
                material={materials.material}
                position={[24.85, 0.295, 30.167]}
                rotation={[0, 1.102, 0]}
                scale={[19.744, 18.88, 19.744]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["16"].geometry}
                material={materials.material}
                position={[8.896, 0.319, -36.931]}
                rotation={[0, 1.102, 0]}
                scale={34.319}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["15"].geometry}
                material={materials.material}
                position={[-31.702, 10.151, -29.898]}
                rotation={[0, 1.102, 0]}
                scale={50.224}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["13"].geometry}
                material={materials.material}
                position={[38.934, 0.328, -11.905]}
                rotation={[0, 1.102, 0]}
                scale={[1.959, 3.546, 1.959]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["2"].geometry}
                material={materials.material}
                position={[-6.871, 0.244, 48.971]}
                rotation={[0, 1.102, 0]}
                scale={34.319}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["11"].geometry}
                material={materials.material}
                position={[28.584, 0.248, -9.395]}
                rotation={[0, -0.469, 0]}
                scale={32.106}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1"].geometry}
                material={materials.material}
                position={[-6.221, 0.476, 66.938]}
                rotation={[Math.PI, -1.102, Math.PI]}
                scale={[50.498, 63.443, 50.498]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["17"].geometry}
                material={materials.material}
                position={[32.656, 0.295, -42.744]}
                rotation={[0, 1.102, 0]}
                scale={[19.744, 18.88, 19.744]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["3"].geometry}
                material={materials.material}
                position={[32.869, 0.253, 37.95]}
                rotation={[-Math.PI, 0.469, -Math.PI]}
                scale={43.338}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["5"].geometry}
                material={materials.material}
                position={[29.986, 0.303, 20.883]}
                rotation={[-Math.PI, 0.469, -Math.PI]}
                scale={3.861}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["8"].geometry}
                material={materials.material}
                position={[30.544, 0.303, 4.521]}
                rotation={[-Math.PI, 0.469, -Math.PI]}
                scale={3.295}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["19"].geometry}
                material={materials.material}
                position={[15.637, -4.104, 46.858]}
                rotation={[0, 1.102, 0]}
                scale={[30.892, 28.615, 30.892]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["14"].geometry}
                material={materials.material}
                position={[42.295, 0.253, -22.707]}
                rotation={[Math.PI, -1.102, Math.PI]}
                scale={43.338}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane.geometry}
                material={materials.Material}
                position={[-15.612, 54.772, -17.144]}
                rotation={[0, 0, -0.379]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane001.geometry}
                material={materials.Material}
                position={[-15.612, 54.776, -17.144]}
                rotation={[0, 0, -1.489]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane002.geometry}
                material={materials.Material}
                position={[-15.612, 54.772, -17.144]}
                rotation={[0, 0, 0.706]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane003.geometry}
                material={materials.Material}
                position={[5.667, 36.697, 48.327]}
                rotation={[0, 0.463, -0.379]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane004.geometry}
                material={materials.Material}
                position={[5.667, 36.702, 48.327]}
                rotation={[0, 0.463, -1.489]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane005.geometry}
                material={materials.Material}
                position={[5.667, 36.697, 48.327]}
                rotation={[0, 0.463, 0.706]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane006.geometry}
                material={materials.Material}
                position={[84.699, 36.697, -52.746]}
                rotation={[0, -0.48, -0.379]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane007.geometry}
                material={materials.Material}
                position={[84.699, 36.702, -52.746]}
                rotation={[0, -0.48, -1.489]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane008.geometry}
                material={materials.Material}
                position={[84.699, 36.697, -52.746]}
                rotation={[0, -0.48, 0.706]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane009.geometry}
                material={materials.Material}
                position={[84.698, 79.705, -37.352]}
                rotation={[-0.135, 0.143, -0.929]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane010.geometry}
                material={materials.Material}
                position={[84.7, 79.709, -37.353]}
                rotation={[-0.135, 0.143, -2.039]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane011.geometry}
                material={materials.Material}
                position={[84.698, 79.705, -37.352]}
                rotation={[-0.135, 0.143, 0.156]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane012.geometry}
                material={materials.Material}
                position={[-80.907, 79.706, 35.004]}
                rotation={[-2.991, -0.593, 2.263]}
                scale={-37.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane013.geometry}
                material={materials.Material}
                position={[-80.909, 79.708, 35.005]}
                rotation={[-2.991, -0.593, 1.154]}
                scale={-37.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane014.geometry}
                material={materials.Material}
                position={[-80.907, 100.729, 35.004]}
                rotation={[-2.598, -0.289, -2.069]}
                scale={-37.311}
            />
            <PerspectiveCamera
                makeDefault={true}
                far={10000}
                near={0.1}
                fov={8.515}
                position={[813.792, 56.695, -43.139]}
                rotation={[-2.98, 1.52, 2.978]}
                scale={68.043}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane015.geometry}
                material={materials.Material}
                position={[51.061, 36.697, 35.485]}
                rotation={[0, -0.48, -0.379]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane016.geometry}
                material={materials.Material}
                position={[51.061, 36.702, 35.485]}
                rotation={[0, -0.48, -1.489]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane017.geometry}
                material={materials.Material}
                position={[51.061, 36.697, 35.485]}
                rotation={[0, -0.48, 0.706]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane018.geometry}
                material={materials.Material}
                position={[-44.243, 73.895, -4.109]}
                rotation={[0, -0.48, -0.379]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane019.geometry}
                material={materials.Material}
                position={[-44.243, 73.9, -4.109]}
                rotation={[0, -0.48, -1.489]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane020.geometry}
                material={materials.Material}
                position={[-44.243, 73.895, -4.109]}
                rotation={[0, -0.48, 0.706]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane021.geometry}
                material={materials.Material}
                position={[-1.46, 36.697, -32.239]}
                rotation={[0, -0.48, -0.379]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane022.geometry}
                material={materials.Material}
                position={[-1.46, 36.702, -32.239]}
                rotation={[0, -0.48, -1.489]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane023.geometry}
                material={materials.Material}
                position={[-1.46, 36.697, -32.239]}
                rotation={[0, -0.48, 0.706]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane024.geometry}
                material={materials.Material}
                position={[25.717, 36.697, -19.982]}
                rotation={[Math.PI, -0.948, 2.762]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane025.geometry}
                material={materials.Material}
                position={[25.717, 36.702, -19.982]}
                rotation={[-Math.PI, -0.948, 1.653]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane026.geometry}
                material={materials.Material}
                position={[25.717, 36.697, -19.982]}
                rotation={[Math.PI, -0.948, -2.435]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane027.geometry}
                material={materials.Material}
                position={[35.862, 64.286, -52.89]}
                rotation={[-Math.PI, -0.596, 2.762]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane028.geometry}
                material={materials.Material}
                position={[35.862, 64.29, -52.89]}
                rotation={[-Math.PI, -0.596, 1.653]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane029.geometry}
                material={materials.Material}
                position={[35.862, 64.286, -52.89]}
                rotation={[-Math.PI, -0.596, -2.435]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane030.geometry}
                material={materials.Material}
                position={[-18.682, 64.286, 52.474]}
                rotation={[Math.PI, 0.193, 2.762]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane031.geometry}
                material={materials.Material}
                position={[-18.682, 64.29, 52.474]}
                rotation={[Math.PI, 0.193, 1.653]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane032.geometry}
                material={materials.Material}
                position={[-18.682, 64.286, 52.474]}
                rotation={[Math.PI, 0.193, -2.435]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane033.geometry}
                material={materials.Material}
                position={[-9.26, 42.068, -3.823]}
                rotation={[-0.135, 0.143, -0.929]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane034.geometry}
                material={materials.Material}
                position={[-9.257, 42.072, -3.824]}
                rotation={[-0.135, 0.143, -2.039]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane035.geometry}
                material={materials.Material}
                position={[-9.26, 42.068, -3.823]}
                rotation={[-0.135, 0.143, 0.156]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane036.geometry}
                material={materials.Material}
                position={[-61.998, 42.068, 34.629]}
                rotation={[-0.135, 0.143, -0.929]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane037.geometry}
                material={materials.Material}
                position={[-61.996, 42.072, 34.629]}
                rotation={[-0.135, 0.143, -2.039]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane038.geometry}
                material={materials.Material}
                position={[-61.998, 42.068, 34.629]}
                rotation={[-0.135, 0.143, 0.156]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane039.geometry}
                material={materials.Material}
                position={[-40.59, 55.042, 7.523]}
                rotation={[0.512, -0.062, -0.521]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane040.geometry}
                material={materials.Material}
                position={[-40.59, 55.046, 7.526]}
                rotation={[0.512, -0.062, -1.63]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane041.geometry}
                material={materials.Material}
                position={[-40.59, 55.042, 7.523]}
                rotation={[0.512, -0.062, 0.565]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane042.geometry}
                material={materials.Material}
                position={[21.822, 75.265, 13.428]}
                rotation={[-0.135, 0.143, -0.929]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane043.geometry}
                material={materials.Material}
                position={[21.824, 75.269, 13.427]}
                rotation={[-0.135, 0.143, -2.039]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane044.geometry}
                material={materials.Material}
                position={[21.822, 75.265, 13.428]}
                rotation={[-0.135, 0.143, 0.156]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane045.geometry}
                material={materials.Material}
                position={[-67.819, 75.265, 17.279]}
                rotation={[-2.878, 1.033, 1.965]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane046.geometry}
                material={materials.Material}
                position={[-67.82, 75.269, 17.277]}
                rotation={[-2.878, 1.033, 0.855]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane047.geometry}
                material={materials.Material}
                position={[-67.819, 75.265, 17.279]}
                rotation={[-2.878, 1.033, 3.05]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane048.geometry}
                material={materials.Material}
                position={[12.967, 59.175, -54.465]}
                rotation={[-2.878, 1.033, 1.965]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane049.geometry}
                material={materials.Material}
                position={[12.965, 59.179, -54.467]}
                rotation={[-2.878, 1.033, 0.855]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane050.geometry}
                material={materials.Material}
                position={[12.967, 59.175, -54.465]}
                rotation={[-2.878, 1.033, 3.05]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane051.geometry}
                material={materials.Material}
                position={[84.699, 36.702, -52.746]}
                rotation={[0.284, -0.392, -0.837]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane052.geometry}
                material={materials.Material}
                position={[-1.751, 60.359, 47.799]}
                rotation={[0, -0.48, -0.379]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane053.geometry}
                material={materials.Material}
                position={[-1.751, 60.364, 47.799]}
                rotation={[0, -0.48, -1.489]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane054.geometry}
                material={materials.Material}
                position={[-1.751, 60.359, 47.799]}
                rotation={[0, -0.48, 0.706]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane055.geometry}
                material={materials.Material}
                position={[-1.751, 60.364, 47.799]}
                rotation={[0.284, -0.392, -0.837]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane056.geometry}
                material={materials.Material}
                position={[9.307, 60.36, -15.463]}
                rotation={[0, -0.48, -0.379]}
                scale={-28.743}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane057.geometry}
                material={materials.Material}
                position={[9.307, 60.363, -15.463]}
                rotation={[0, -0.48, -1.489]}
                scale={-28.743}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane058.geometry}
                material={materials.Material}
                position={[9.307, 60.36, -15.463]}
                rotation={[0, -0.48, 0.706]}
                scale={-28.743}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane059.geometry}
                material={materials.Material}
                position={[9.307, 60.363, -15.463]}
                rotation={[0.284, -0.392, -0.837]}
                scale={-28.743}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane060.geometry}
                material={materials.Material}
                position={[56.833, 60.36, -109.408]}
                rotation={[0, -0.48, -0.379]}
                scale={-28.743}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane061.geometry}
                material={materials.Material}
                position={[56.833, 60.363, -109.408]}
                rotation={[0, -0.48, -1.489]}
                scale={-28.743}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane062.geometry}
                material={materials.Material}
                position={[56.833, 60.36, -109.408]}
                rotation={[0, -0.48, 0.706]}
                scale={-28.743}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane063.geometry}
                material={materials.Material}
                position={[56.833, 60.363, -109.408]}
                rotation={[0.284, -0.392, -0.837]}
                scale={-28.743}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane064.geometry}
                material={materials.Material}
                position={[59.876, 36.697, -76.373]}
                rotation={[0, 0.351, -0.379]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane065.geometry}
                material={materials.Material}
                position={[59.876, 36.702, -76.373]}
                rotation={[0, 0.351, -1.489]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane066.geometry}
                material={materials.Material}
                position={[59.876, 36.697, -76.373]}
                rotation={[0, 0.351, 0.706]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane067.geometry}
                material={materials.Material}
                position={[59.876, 36.702, -76.373]}
                rotation={[0.286, 0.408, -1.064]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane068.geometry}
                material={materials.Material}
                position={[-83.368, 36.697, 86.282]}
                rotation={[0, -0.391, -0.379]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane069.geometry}
                material={materials.Material}
                position={[-83.368, 36.702, 86.282]}
                rotation={[0, -0.391, -1.489]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane070.geometry}
                material={materials.Material}
                position={[-83.368, 36.697, 86.282]}
                rotation={[0, -0.391, 0.706]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane071.geometry}
                material={materials.Material}
                position={[-83.368, 36.702, 86.282]}
                rotation={[0.275, -0.307, -0.863]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane072.geometry}
                material={materials.Material}
                position={[-83.368, 74.086, 86.282]}
                rotation={[Math.PI, -0.91, 2.762]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane073.geometry}
                material={materials.Material}
                position={[-83.368, 74.091, 86.282]}
                rotation={[Math.PI, -0.91, 1.653]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane074.geometry}
                material={materials.Material}
                position={[-83.368, 74.086, 86.282]}
                rotation={[Math.PI, -0.91, -2.435]}
                scale={-50.707}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane075.geometry}
                material={materials.Material}
                position={[-83.368, 74.091, 86.282]}
                rotation={[2.692, -0.934, 1.823]}
                scale={-50.707}
            />
        </group>
    );
}

useGLTF.preload("/models/alpha_city_scene1.glb");
